# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ""
author: Md. Khairul Islam
email: khairulislamtanim@gmail.com
# logo: logo.png
copyright: "2024"
description: >- # this means to ignore newlines until "baseurl:"
  This book lists the Machine Learning and Data Mining 
  related conferences with their important date and list 
  of accepted papers.

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/khairulislam/ML-conferences # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
# html:
#   use_issues_button: true
#   use_repository_button: true
#   use_edit_page_button: true

sphinx:
  config:
    html_context:
      default_mode: auto
    html_theme_options:
      logo:
        image_dark: logo-dark.png
        image_light: logo-light.png
      repository_url: https://github.com/khairulislam/ML-conferences
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true
      
    # html_static_path:
    #   - "logo_light.png"
    #   - "logo_dark.png"
    bibtex_reference_style: author_year # or label, super, \supercite
    # suppress_warnings:
    #   ["mystnb.unknown_mime_type", "myst.domains", "mystnb.mime_priority"]
    # copybutton_prompt_text: "$"
    # language: en
    
